### ISSUE TITLE
setup.py fails

### ISSUE THREAD

**Issue by scottrk2** [clintval/snv-spectrum#11]
Python version: 3.6

Mes-MacBook-Air:snv-spectrum-master SRK$ python setup.py build
running build
running build_py
file snv_spectrum.py (for module snv_spectrum) not found
file snv_spectrum.py (for module snv_spectrum) not found

**Comment by clintval** [comment]
Can you not just `pip install`? Will look into this tomorrow.

**Comment by clintval** [comment]
Fixed in #12.

I had a useless line in `setup.py` which prevented a complete build when using distutils instead of pip.
