### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by scottrk2** [clintval/snv-spectrum#13]
Not sure if this is a problem with pip or an issue with snv-spectrum. 

Using pip install snv-spectrum gives the following error: "Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/mf/28775vz108sbnym4j9yd83w00000gn/T/pip-build-gypnrbfk/snv-spectrum/"

Looking at similar error codes suggests that it's due to an old version of setuptools, but I have 38.6.0 installed, so not likely the issue. Pip version 9.0.1.

**Comment by clintval** [comment]
This package is released on PyPi so if you would like `v.02.0`, this command will work:

```bash
❯ pip install snv_spectrum
```

For a bleeding edge or development install.

_With pip:_
```bash
❯ https://github.com/clintval/snv-spectrum.git && cd snv-spectrum
❯ git checkout master && git pull
❯ sudo pip install .
# or `sudo pip install -e .` for a development install
```

_With distutils:_
```bash
❯ https://github.com/clintval/snv-spectrum.git && cd snv-spectrum
❯ git checkout master && git pull
❯ python3.6 setup.py build
❯ sudo python3.6 setup.py install
```

**Comment by clintval** [comment]
I just tried all three and they worked. Closing for now. Keep me posted though, on your progress.

**Comment by clintval** [comment]
If you want to contribute too you can follow these instructions:

https://github.com/clintval/snv-spectrum#contributing
